
// Generated By Leetcode2IDE
#include <bits/stdc++.h>
using namespace std;



class Solution {
public:
    vector<int> findMissingAndRepeatedValues(vector<vector<int>>& grid) {
        int n = grid.size();
        for(int i = 1; i<= pow(n,2);i++)
        {
            
        }
    }
};


int main() {
	
	Solution leetcode2IDE;
	vector<vector<int>> grid1 = {{1,3},{2,2}};
	vector<int> output_1 = {2,4};
	if(leetcode2IDE.findMissingAndRepeatedValues(grid1)==output_1){
		cout << "Sample #1 : Accepted" << endl;
	}else{
		cout << "Sample #1 : Wrong Answer" << endl;
	}

	vector<vector<int>> grid2 = {{9,1,7},{8,9,2},{3,4,6}};
	vector<int> output_2 = {9,5};
	if(leetcode2IDE.findMissingAndRepeatedValues(grid2)==output_2){
		cout << "Sample #2 : Accepted" << endl;
	}else{
		cout << "Sample #2 : Wrong Answer" << endl;
	}

	


	return 0;
}
	